version = 0.1

[default.deploy.parameters]
stack_name = "alexa-ai-skill"
resolve_s3 = true
s3_prefix = "alexa-ai-skill"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
image_repositories = []

[default.build.parameters]
cached = true
parallel = true
