version = 0.1

[default.deploy.parameters]
stack_name = "gemini-skill"
resolve_s3 = true
s3_prefix = "gemini-skill"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

[default.build.parameters]
cached = true
parallel = true
